### ISSUE TITLE
Additional Parameter Binding

### ISSUE THREAD

**Issue by Jak893** [ALMMa/datatables.aspnet#20] opened 2015-07-24 11:34 UTC
Hi,

I'm hoping this is not an issue and more an error on my part, but the numerous ways I've tried to resolve this makes me think something might be wrong.

Within the ```IDataTablesRequest``` I can see that there is an ability to post up a set of additional data parameters. I am hoping to achieve this by using the ```data``` option within the DataTables AJAX options.
```
data: function(d) {
                        var builtInParam = parseQueryString("routeValues");
                        if (builtInParam)
                            d.AditionalParameters = {"builtin": builtInParam};
                    },
```
I have also tried just passing it up as a standard value without the use of a function, but still on the server side, I am getting null on the AdditionalParameters.

Any advice or is this an actual issue?

Thanks for a great library all the same, has been fantastic so far!

**Comment by ALMMa** [comment] 2015-07-24 13:05
Closed as duplicate of #19.

You should explicitly enable aditional parameters parsing by passing your parse function on DataTables registration.

**Closed by ALMMa** 2015-07-24 13:05 UTC
Labels: duplicate
